export const finiteeIconMapper = {
  /*   'bpost-po-large': 'assets/badges/md-bpost-po-large.svg',
    'bpost-po-small': 'assets/badges/md-bpost-po-small.svg',
    'bpost-so-large': 'assets/badges/md-bpost-so-large.svg',
    'bpost-so-small': 'assets/badges/md-bpost-so-small.svg',
    'bpost-ss-large': 'assets/badges/md-bpost-ss-large.svg',
    'bpost-ss-small': 'assets/badges/md-bpost-ss-small.svg',
    'npost-po-large': 'assets/badges/md-npost-po-large.svg',
    'npost-po-small': 'assets/badges/md-npost-po-small.svg',
    'npost-so-large': 'assets/badges/md-npost-so-large.svg',
    'npost-so-small': 'assets/badges/md-npost-so-small.svg',
    'npost-ss-large': 'assets/badges/md-npost-ss-large.svg',
    'npost-ss-small': 'assets/badges/md-npost-ss-small.svg',
    'post-po-large': 'assets/badges/md-post-po-large.svg',
    'post-po-small': 'assets/badges/md-post-po-small.svg',
    'post-so-large': 'assets/badges/md-post-so-large.svg',
    'post-so-small': 'assets/badges/md-post-so-small.svg',
    'post-ss-large': 'assets/badges/md-post-ss-large.svg',
    'post-ss-small': 'assets/badges/md-post-ss-small.svg',
    'totem-po-large': 'assets/badges/md-totem-po-large.svg',
    'totem-po-small': 'assets/badges/md-totem-po-small.svg',
    'totem-so-large': 'assets/badges/md-totem-so-large.svg',
    'totem-so-small': 'assets/badges/md-totem-so-small.svg',
    'totem-ss-large': 'assets/badges/md-totem-ss-large.svg',
    'totem-ss-small': 'assets/badges/md-totem-ss-small.svg',
   */
  'ambassador-po-large': 'assets/custom-ion-icons/md-ambassador-po-large.svg',
  'ambassador-po-small': 'assets/custom-ion-icons/md-ambassador-po-small.svg',
  'ambassador-so-large': 'assets/custom-ion-icons/md-ambassador-so-large.svg',
  'ambassador-so-small': 'assets/custom-ion-icons/md-ambassador-so-small.svg',
  'ambassador-ss-large': 'assets/custom-ion-icons/md-ambassador-ss-large.svg',
  'ambassador-ss-small': 'assets/custom-ion-icons/md-ambassador-ss-small.svg',
  // announcement: 'assets/custom-ion-icons/md-announcement.svg',
  basic: 'assets/custom-ion-icons/md-basic.svg',
  
  blockbusiness: 'assets/custom-ion-icons/md-blockbusiness.svg',
  blockconnection: 'assets/custom-ion-icons/md-blockconnection.svg',
  blocknonp: 'assets/custom-ion-icons/md-blocknonp.svg',
  bluearrowdown: 'assets/custom-ion-icons/md-bluearrowdown.svg',
  bluearrowup: 'assets/custom-ion-icons/md-bluearrowup.svg',
  bluebusiness: 'assets/custom-ion-icons/md-bluebusiness.svg',
  bluechat: 'assets/custom-ion-icons/md-bluechat.svg',
  onhold:'assets/custom-ion-icons/on-hold.svg',
  bluecur: 'assets/custom-ion-icons/md-bluecur.svg',
  bluemenu: 'assets/custom-ion-icons/md-bluemenu.svg',
  bluepost: 'assets/custom-ion-icons/md-bluepost.svg',
  bluesearch: 'assets/custom-ion-icons/sonar-search-icon.svg',
  bluetotem: 'assets/custom-ion-icons/md-bluetotem.svg',
  blueuser: 'assets/custom-ion-icons/md-blueuser.svg',
  bu: 'assets/custom-ion-icons/md-bu.svg',
  cameraicon: 'assets/custom-ion-icons/md-cameraicon.svg',
  chatwhite: 'assets/custom-ion-icons/md-chatwhite.svg',
  city: 'assets/custom-ion-icons/md-city.svg',
  city2: 'assets/custom-ion-icons/md-city2.svg',
  //close: 'assets/custom-ion-icons/md-close.svg',
  connectedbu: 'assets/custom-ion-icons/md-connectedbu.svg',
  connectedfu: 'assets/custom-ion-icons/md-connectedfu.svg',
  connectednpu: 'assets/custom-ion-icons/md-connectednpu.svg',
  contact: 'assets/custom-ion-icons/md-contact.svg',
  createtotem: 'assets/custom-ion-icons/md-createtotem.svg',
  'crypto-act': 'assets/custom-ion-icons/md-crypto-act.svg',
  crypto: 'assets/custom-ion-icons/md-crypto.svg',
  currentlocation: 'assets/custom-ion-icons/md-currentlocation.svg',
  delete: 'assets/custom-ion-icons/md-delete.svg',
  'donate-po-large': 'assets/custom-ion-icons/md-donate-po-large.svg',
  'donate-po-small': 'assets/custom-ion-icons/md-donate-po-small.svg',
  'donate-so-large': 'assets/custom-ion-icons/md-donate-so-large.svg',
  'donate-so-small': 'assets/custom-ion-icons/md-donate-so-small.svg',
  'donate-ss-large': 'assets/custom-ion-icons/md-donate-ss-large.svg',
  'donate-ss-small': 'assets/custom-ion-icons/md-donate-ss-small.svg',
  donation: 'assets/custom-ion-icons/donations.svg',
  doubt: 'assets/custom-ion-icons/md-doubt.svg',
  ecard: 'assets/custom-ion-icons/md-ecard.svg',
  //edit: 'assets/custom-ion-icons/md-edit.svg',
  'edit-white': 'assets/custom-ion-icons/md-edit-white.svg',
  editt: 'assets/custom-ion-icons/md-editt.svg',
  edu: 'assets/custom-ion-icons/md-edu.svg',
  'email-w': 'assets/custom-ion-icons/md-email-w.svg',
  email: 'assets/custom-ion-icons/md-email.svg',
  eyeclose: 'assets/custom-ion-icons/md-eyeclose.svg',
  eyeopen: 'assets/custom-ion-icons/md-eyeopen.svg',
  firevpb: 'assets/custom-ion-icons/md-firevpb.svg',
  fu: 'assets/custom-ion-icons/md-fu.svg',
  galleryicon: 'assets/custom-ion-icons/md-galleryicon.svg',
  hamburger: 'assets/custom-ion-icons/md-hamburger.svg',
  inflows: 'assets/custom-ion-icons/md-inflows.svg',
  'inflowset-2': 'assets/custom-ion-icons/md-inflowset-2.svg',
  inflowset: 'assets/custom-ion-icons/md-inflowset.svg',
  inflowsred: 'assets/custom-ion-icons/md-inflowsred.svg',
  location: 'assets/custom-ion-icons/md-location.svg',
  'location-w': 'assets/custom-ion-icons/md-location-w.svg',
  lock: 'assets/custom-ion-icons/md-lock.svg',
  mail: 'assets/custom-ion-icons/md-mail.svg',
  menui: 'assets/custom-ion-icons/md-menui.svg',
  more: 'assets/custom-ion-icons/md-more.svg',
  msgpost: 'assets/custom-ion-icons/md-msgpost.svg',
  multibu: 'assets/custom-ion-icons/md-multibu.svg',
  multifu: 'assets/custom-ion-icons/md-multifu.svg',
  multipu: 'assets/custom-ion-icons/md-multipu.svg',
  navigate: 'assets/custom-ion-icons/md-navigate.svg',
  npu: 'assets/custom-ion-icons/md-npu.svg',
  nonprofit: 'assets/custom-ion-icons/nonprofits.svg',
  paypal: 'assets/custom-ion-icons/md-paypal.svg',
  phone: 'assets/custom-ion-icons/md-phone.svg',
  phonecall: 'assets/custom-ion-icons/md-phonecall.svg',
  'phonecall-w': 'assets/custom-ion-icons/md-phonecall-w.svg',
  postby: 'assets/custom-ion-icons/md-postby.svg',
  postby2: 'assets/custom-ion-icons/md-postby2.svg',
  privacy: 'assets/custom-ion-icons/md-privacy.svg',
  'recommend-po-large': 'assets/custom-ion-icons/md-recommend-po-large.svg',
  'recommend-po-small': 'assets/custom-ion-icons/md-recommend-po-small.svg',
  'recommend-so-large': 'assets/custom-ion-icons/md-recommend-so-large.svg',
  'recommend-so-small': 'assets/custom-ion-icons/md-recommend-so-small.svg',
  'recommend-ss-large': 'assets/custom-ion-icons/md-recommend-ss-large.svg',
  'recommend-ss-small': 'assets/custom-ion-icons/md-recommend-ss-small.svg',
  'refer-po-large': 'assets/custom-ion-icons/md-refer-po-large.svg',
  'refer-po-small': 'assets/custom-ion-icons/md-refer-po-small.svg',
  'refer-so-large': 'assets/custom-ion-icons/md-refer-so-large.svg',
  'refer-so-small': 'assets/custom-ion-icons/md-refer-so-small.svg',
  'refer-ss-large': 'assets/custom-ion-icons/md-refer-ss-large.svg',
  'refer-ss-small': 'assets/custom-ion-icons/md-refer-ss-small.svg',
  referbusiness: 'assets/custom-ion-icons/md-referbusiness.svg',
  'referbusiness-w': 'assets/custom-ion-icons/md-referbusiness-w.svg',
  'referconnection-w': 'assets/custom-ion-icons/md-referconnection-w.svg',
  referconnection: 'assets/custom-ion-icons/md-referconnection.svg',
  refernonp: 'assets/custom-ion-icons/md-refernonp.svg',
  referuser: 'assets/custom-ion-icons/md-referuser.svg',
  rel: 'assets/custom-ion-icons/md-rel.svg',
  removeconnection: 'assets/custom-ion-icons/md-removeconnection.svg',
  renonp: 'assets/custom-ion-icons/md-renonp.svg',
  reportbusiness: 'assets/custom-ion-icons/md-reportbusiness.svg',
  resend: 'assets/custom-ion-icons/md-resend.svg',
  'right-arrow': 'assets/custom-ion-icons/right-arrow.svg',
  rolodoxbig: 'assets/custom-ion-icons/md-rolodoxbig.svg',
  sales: 'assets/custom-ion-icons/md-sales.svg',
  sales_listing: 'assets/custom-ion-icons/sales_listing.svg',
  unconnected:'assets/markers/uu.svg',
  acceptedgreendot:'assets/markers/greendoticon.svg',
  reddoticongreeting:'assets/markers/reddoticongreeting.svg',
  timeouticon:'assets/markers/timeouticon.svg',
  human:'assets/custom-ion-icons/human.png',
  rejectedreddot:'assets/markers/reddoticon.svg',
  searchi: 'assets/custom-ion-icons/md-searchi.svg',
  terminate: 'assets/custom-ion-icons/md-terminate.svg',
  totem: 'assets/custom-ion-icons/md-totem.svg',
  totemadd: 'assets/custom-ion-icons/create-totem-no-circle.svg',
  totefill: 'assets/custom-ion-icons/md-totefill.svg',
  traits: 'assets/custom-ion-icons/md-traits.svg',
  verifyemail: 'assets/custom-ion-icons/md-verifyemail.svg',
  videoicon: 'assets/custom-ion-icons/md-videoicon.svg',
  'visa-act': 'assets/custom-ion-icons/md-visa-act.svg',
  'website-w': 'assets/custom-ion-icons/md-website-w.svg',
  website: 'assets/custom-ion-icons/md-website.svg',
  work: 'assets/custom-ion-icons/md-work.svg',
  flame: 'assets/custom-ion-icons/flame-blue.svg',
  'flame-active': 'assets/custom-ion-icons/flame-orange.svg',
  'blue-carousel':'assets/custom-ion-icons/Greetingiconwhitebluecarousel.svg',
  'Greeting-icon-white-green-carousel':'assets/custom-ion-icons/GreetingbuttonCarouselgreen.svg',
  'orange-carousel':'assets/custom-ion-icons/orange-carousel.svg',
'Event_thumbnail':'assets/custom-ion-icons/Event_thumbnail.svg',
'Serviceavailable_thumbnail':'assets/custom-ion-icons/Serviceavailable_thumbnail.svg',
'servicerequired_thumbnail':'assets/custom-ion-icons/servicerequired_thumbnail.svg',
'saleslisting_thumbnail':'assets/custom-ion-icons/saleslisting_thumbnail.svg',
'sonar-donation':'assets/custom-ion-icons/sonar_donations.svg',
'sonar-event':'assets/custom-ion-icons/sonar_event.svg',
'sonarsearch-location':'assets/custom-ion-icons/sonarsearch_location.svg',
'Donation':'assets/custom-ion-icons/Donation.svg',
  'green-handshake': 'assets/custom-ion-icons/md-green-handshake.svg',
  'no-handshake': 'assets/custom-ion-icons/md-no-handshake.svg',
  'greeting': 'assets/custom-ion-icons/md-handshake.svg',
  'no-profile': 'assets/custom-ion-icons/md-no-profile.svg',
  'no-hi': 'assets/custom-ion-icons/md-no-hi.svg',
  'no-dollar': 'assets/custom-ion-icons/md-no-dollar.svg',
  'blue-location': 'assets/custom-ion-icons/md-blue-location.svg',
  'chat': 'assets/custom-ion-icons/md-chat.svg',
  'chatwhitenew': 'assets/custom-ion-icons/chat-white.svg',
  'add': 'assets/icons/screen-wise-icons/Canvas screens icons as svg/Creat post + icon.svg',

  'chat-camera': 'assets/custom-ion-icons/picturecamera.svg',
  'chat-video':
    'assets/icons/screen-wise-icons/Sonar icons/Chat screen video icon.svg',
  'chat-gallery': 'assets/custom-ion-icons/picturegallery.svg',
  'chat-search': 'assets/custom-ion-icons/search.svg',
  'chat-delete': 'assets/custom-ion-icons/chatdelete.svg',
  'chat-forward': 'assets/custom-ion-icons/chatforward.svg',
  'chat-reply': 'assets/custom-ion-icons/chatreply.svg',
  'chat-copy': 'assets/custom-ion-icons/chatcopy.svg',
  'chat-plus': 'assets/custom-ion-icons/plus.svg',
  'chat-back': 'assets/custom-ion-icons/navigateback.svg',
  'chat-3dots': 'assets/custom-ion-icons/3dots.svg',
  'chat-mute': 'assets/custom-ion-icons/mute.svg',
  'chat-blue': 'assets/custom-ion-icons/twoblueticks.svg',
  'chat-hamburger': 'assets/custom-ion-icons/hamburger.svg',
  'chat-brokenlink': 'assets/custom-ion-icons/broken-link-icon.svg',
  'chat-brokenlinkcolor': 'assets/custom-ion-icons/broken-link-iconcolor.svg',
  'chat-exclamation': 'assets/custom-ion-icons/chatexclamation.svg',

  'greeting-blink': 'assets/custom-ion-icons/md-green-handshake.svg',
  'sonar-setting': 'assets/custom-ion-icons/sonar/sonar-setting.svg',
  'greeting-no-circle': 'assets/custom-ion-icons/sonar/greeting-no-circle.svg',
  'view-on-map': 'assets/custom-ion-icons/sonar/view-on-map.svg',
  'create-totem': 'assets/custom-ion-icons/sonar/create-totem-blue.svg',
  'viewing-binoculars': 'assets/custom-ion-icons/viewing-binoculars.svg',
  'sonar-make-invisible':
    'assets/custom-ion-icons/sonar/sonar-make-invisible-blue.svg',
  'sonar-make-visible':
    'assets/custom-ion-icons/sonar/sonar-make-visible-blue.svg',
  'greeting-accept': 'assets/custom-ion-icons/sonar/greeting-accept.svg',
  'greeting-reject': 'assets/custom-ion-icons/sonar/greeting-reject.svg',
  'greeting-sent': 'assets/custom-ion-icons/sonar/greeting-sent.svg',
  'close-icon': 'assets/custom-ion-icons/cross-icon.svg',
  //'no-handshake': 'assets/custom-ion-icons/md-no-handshake.svg',
  // 'greeting': 'assets/custom-ion-icons/Greetingiconwhitebluecarousel.svg',
  //'no-profile': 'assets/custom-ion-icons/md-no-profile.svg',
  //'no-hi': 'assets/custom-ion-icons/md-no-hi.svg',
  //'no-dollar': 'assets/custom-ion-icons/md-no-dollar.svg',
  //'blue-location': 'assets/custom-ion-icons/md-blue-location.svg',
  //'chat': 'assets/custom-ion-icons/md-chat.svg',
  'chat-ignore': 'assets/custom-ion-icons/chat-ignore.svg',

  //   Product Action Sheet
  'edit-product':
    'assets/icons/screen-wise-icons/Canvas screens icons as svg/Edit icon.svg',
  'delete-product':
    'assets/icons/screen-wise-icons/Canvas screens icons as svg/Menu delete icon.svg',

  //   Events
  'bell': 'assets/icons/screen-wise-icons/Canvas screens icons as svg/Notification icon with no number superimposed on it.svg',

  //   Create event
  'down-arrow':
    'assets/icons/screen-wise-icons/Sonar icons/Down arrow icon.svg',

  //   Three dots
  'three-dots':
    'assets/icons/screen-wise-icons/Home screen icons/Product tile 3 dot icon.svg',

    'beamicon':'assets/icons/screen-wise-icons/Canvas screens icons/Beam icon.svg',

  //   Header Back Button
  'back-button':
    'assets/icons/screen-wise-icons/Canvas screens icons as svg/Back icon.svg',
  'back-button-white':
    'assets/icons/screen-wise-icons/Canvas screens icons as svg/Back icon-white.svg',

  //   Nonprofit
  'made-donation':
    'assets/icons/screen-wise-icons/Nonprofit Home screen menu icons/Nonprofit menu view donation requests icon.svg',

  'comment-favour-filled':
    'assets/icons/screen-wise-icons/Canvas screens icons as svg/Comments screen favor icon color.svg',
  'comment-favour-outlined':
    'assets/icons/screen-wise-icons/Canvas screens icons as svg/Comments screen favor icon black and white.svg',

  beam: 'assets/icons/screen-wise-icons/Canvas screens icons as svg/Beam icon.svg',

  'comment-attach':
    'assets/icons/screen-wise-icons/Canvas screens icons as svg/Comments screen Attach icon .svg',

  'comment-send':
    'assets/icons/screen-wise-icons/Sonar icons/Chat sceen send icon not highlighted.svg',

  //Business
  'announcement-edit': 'assets/icons/business/edit-white.svg',
  'report-business': 'assets/icons/business/Home-screen-Business-report-icon.svg',
  'b-connect-with-business': 'assets/icons/business/BusinessConnectionRequest.svg',
  'b-request-sent': 'assets/icons/business/BusinessConnectionRequestPending.svg',
  'b-request-accepted': 'assets/icons/business/BusinessConnected.svg',
  'f-connect-with-business': 'assets/icons/business/FreeConnectionRequest.svg',
  'f-request-sent': 'assets/icons/business/FreeConnectionRequestPending.svg',
  'f-request-accepted': 'assets/icons/business/FreeConnected.svg',
  'business-location': 'assets/icons/business/location.svg',
  'business-email': 'assets/icons/business/email.svg',
  'business-phone': 'assets/icons/business/phone.svg',
  'business-website': 'assets/icons/business/website.svg',
  'see-more': 'assets/icons/business/see-more.svg',
  'see-less': 'assets/icons/business/see-less.svg',
  'anonymous2': 'assets/icons/business/anonymous2.svg',
  'announcement': 'assets/icons/business/announcement.svg',
  'announcement-blue': 'assets/icons/business/Business Annoucnement icon blue.svg',
  'dots': 'assets/icons/business/3dot.svg',
  'ConnectionsentCarousel':'assets/custom-ion-icons/ConnectionsentCarousel.svg',
  'chaticoninchat':'assets/custom-ion-icons/chaticoninchat.svg',
  "connected-members-chat": 'assets/icons/business/connected-members-chat.svg',
  "edit": 'assets/icons/business/edit.svg',
  'business-recommend': 'assets/icons/business/business-recommend.svg',
  'business-report': 'assets/icons/business/business-report.svg',
  'stop-inflows': 'assets/icons/business/stop-inflows.svg',
  'business-block': 'assets/custom-ion-icons/md-blockbusiness.svg',
  'canvas-filter': 'assets/custom-ion-icons/canvas-filter-icon.svg',
  'posting-multiple-picture':'assets/custom-ion-icons/posting-multiple-picture.svg',
  'posting-video': 'assets/custom-ion-icons/posting-video-icon.svg',
  'post-chat':'assets/icons/screen-wise-icons/Canvas screens icons as svg/Post screen chat icon.svg',
  'post-invite':'assets/icons/screen-wise-icons/Canvas screens icons as svg/Post screen Invite to beam icon.svg',
  'beam-post': 'assets/icons/screen-wise-icons/Canvas screens icons as svg/Beam icon.svg',



  // Right Menu Icons
  'right-menu-rolodex': 'assets/icons/sidemenu/rolodex.svg',
  'right-menu-sales': 'assets/icons/sidemenu/sales-listing.svg',
  'right-menu-account-management': 'assets/icons/sidemenu/account-management.svg',
  'right-menu-app-info': 'assets/icons/sidemenu/app-info.svg',
  'right-menu-display': 'assets/icons/sidemenu/display.svg',
  'right-menu-events': 'assets/icons/sidemenu/events.svg',
  'right-menu-faqs': 'assets/icons/sidemenu/faqs.svg',
  'right-menu-help': 'assets/icons/sidemenu/help.svg',
  'right-menu-report': 'assets/icons/sidemenu/report.svg',
  'right-menu-invite-to-finitee': 'assets/icons/sidemenu/invite-to-finitee.svg',
  'right-menu-legal': 'assets/icons/sidemenu/legal.svg',
  'right-menu-logout': 'assets/icons/sidemenu/logout.svg',
  'right-menu-open-menu': 'assets/icons/sidemenu/open-menu.svg',
  'right-menu-privacy-settings': 'assets/icons/sidemenu/privacy-settings.svg',
  'right-menu-settings': 'assets/icons/sidemenu/settings.svg',
  'right-menu-shopping-list': 'assets/icons/sidemenu/shopping-list.svg',
  'right-menu-tutorials': 'assets/icons/sidemenu/tutorials.svg',
  'right-menu-statistics': 'assets/icons/sidemenu/statistics.svg',
  'right-menu-wallet': 'assets/icons/sidemenu/wallet.svg',
  'right-menu-service-main': 'assets/icons/sidemenu/services-main.svg',
  'right-menu-service-required': 'assets/icons/sidemenu/services-required.svg',
  'right-menu-service-alert': 'assets/icons/sidemenu/services-alert.svg',
  'right-menu-service-available':'assets/icons/sidemenu/services-available.svg',
  'right-menu-eprofile': 'assets/icons/sidemenu/eprofile.svg',
  'right-menu-ecard': 'assets/icons/sidemenu/ecard.svg',
  'right-menu-profile': 'assets/icons/sidemenu/free-user-profile.svg',
  'right-menu-privacy-policy': 'assets/icons/sidemenu/privacy-policy.svg',
  'right-menu-terms-condition': 'assets/icons/sidemenu/terms-conditions.svg',
  'right-menu-community-guidelines': 'assets/icons/sidemenu/community-guidelines.svg',

  //bottom menu
  'tab-map-black': 'assets/icons/tabs/map-black.svg',
  'tab-map-blue': 'assets/icons/tabs/map-blue.svg',
  'tab-bhome-black': 'assets/icons/tabs/bhome-black.svg',
  'tab-bhome-blue': 'assets/icons/tabs/bhome-blue.svg',
  'tab-canvas-black': 'assets/icons/tabs/canvas-black.svg',
  'tab-canvas-blue': 'assets/icons/tabs/canvas-blue.svg',
  'tab-connection-black': 'assets/icons/tabs/connection-black.svg',
  'tab-connection-blue': 'assets/icons/tabs/connection-blue.svg',
  'tab-inflows-black': 'assets/icons/tabs/inflows-black.svg',
  'tab-inflows-blue': 'assets/icons/tabs/inflows-blue.svg',
  'tab-search-black': 'assets/icons/tabs/search-black.svg',
  'tab-search-blue': 'assets/icons/tabs/search-blue.svg',
  'tab-chat-black': 'assets/icons/tabs/chat-black.svg',
  'tab-chat-blue': 'assets/icons/tabs/chat-blue.svg',
  'tab-more-black': 'assets/icons/tabs/more.svg',
  'tab-more-blue': 'assets/icons/tabs/more.svg',

  //events icon
  'heat-map-icon': 'assets/icons/screen-wise-icons/event-icons/Heatmap-icon.svg',
  'location-circle-blue-icon': 'assets/icons/screen-wise-icons/event-icons/Location-icon.svg',
  'eventdate': 'assets/icons/screen-wise-icons/event-icons/Events-Carousel-Date-icon.svg',
  'eventclock': 'assets/icons/screen-wise-icons/event-icons/Events-Carousel-Time-icon.svg',
  

  //free user icon
  'free-user-connected-white-icon':'assets/icons/screen-wise-icons/free-user/Free-user-connected-icon-only-white.svg',
  'free-user-request-white-icon':'assets/icons/screen-wise-icons/free-user/Free-user-connection-request-icon-only-white.svg',
  'free-user-pending-white-icon':'assets/icons/screen-wise-icons/free-user/Free-user-connection-request-pending-icon-only-white.svg',
  'free-user-recieved-white-icon': 'assets/icons/screen-wise-icons/free-user/new.svg',
  'free-user-post':'assets/icons/screen-wise-icons/free-user/Post-Icon-Menu-choice.svg',
  'free-user-trait-post':'assets/icons/screen-wise-icons/free-user/Trait-post-icon-menu-choice.svg',
  'user-block': 'assets/custom-ion-icons/user-block.svg',
  'user-report':'assets/icons/screen-wise-icons/free-user/Menu-report-user-icon.svg',
  'user-inflows-color':'assets/icons/screen-wise-icons/free-user/Menu-Inflows-Icon-color.svg',
  'send-connection-sonar-icon':'assets/icons/screen-wise-icons/free-user/send_conn_sonar.svg',
  'connected-sonar-icon':'assets/icons/screen-wise-icons/free-user/Connected - Carousel.svg',
  'send-greeting-blue':'assets/icons/screen-wise-icons/free-user/Greeting button Carousel blue.svg',
  'sent-greeting-orange':'assets/icons/screen-wise-icons/free-user/Greeting button Carousel orange.svg',
  'receive-greeting-green':'assets/icons/screen-wise-icons/free-user/Greeting button Carousel Green.svg',
  'no-traits-icon':'assets/icons/screen-wise-icons/free-user/no_trait_icon.svg',
  'connection-req-sent-icon':'assets/icons/screen-wise-icons/free-user/connection_req_sent.svg',
  'connection-req-recieved-icon':'assets/icons/screen-wise-icons/free-user/connection-req-recieved.svg',
};

